feat-language-switcher-integration
purplena/resume-on-laravel pull request #5
Opened 2024-03-04 14:31 UTC by purplena

2024-03-04 18:59 UTC, stephdotnet reviewed
Keep going, you're getting better by every PR you make

2024-03-04 18:59 UTC, stephdotnet commented on resources/css/_1_hero.scss
> +    margin-top: 71px;
Essayer d'utiliser les variables ou design tokens de tailwind, en scss : https://tailwindcss.com/docs/customizing-spacing

Sinon définir (ou trouver un moyen) de réutiliser les design token tailwind

2024-03-04 18:59 UTC, stephdotnet commented on resources/css/main.scss
> +    // width: 100%;
supprimer ?

2024-03-04 18:59 UTC, stephdotnet commented on resources/views/components/language_switcher.blade.php
> +                    <img class="w-[32px]" src="{{ asset('images/flags/' . $locale_name . '-flag.png') }}"
Voir si possible d'utiliser w-6 à la place
https://tailwindcss.com/docs/customizing-spacing

2024-03-04 18:59 UTC, stephdotnet commented on resources/views/components/language_switcher.blade.php
> +                <img class="w-[32px]" src="{{ asset('images/flags/' . $locale_name . '-flag.png') }}"
Voir si possible d'utiliser w-6 à la place
https://tailwindcss.com/docs/customizing-spacing

2024-03-04 18:59 UTC, stephdotnet commented on resources/views/components/language_switcher.blade.php
> +                <a class="flex flex-row gap-2 " href={{ url('language/') . '/' . $available_locale }}>
utiliser plutôt route('route.name', ['locale' => $available_locale]) et (route.name est un example, a toi de donner un nom à ta route et de l'utiliser en adéquation)

2024-03-04 18:59 UTC, stephdotnet commented on resources/views/components/language_switcher.blade.php
> +            <div class="flex flex-row gap-2 cursor-pointer" id="current-language">
faire un component pour éviter de la duplication du code (peut être flag component)

2024-03-04 18:59 UTC, stephdotnet commented on resources/views/components/navbar.blade.php
> +                    <a href="/">
remplacer par route('home')

2024-03-04 19:00 UTC, stephdotnet approved these changes

2024-03-11 08:47 UTC, purplena commented on resources/views/components/language_switcher.blade.php
> +                <a class="flex flex-row gap-2 " href={{ url('language/') . '/' . $available_locale }}>
done!

2024-03-11 08:47 UTC, purplena commented on resources/views/components/language_switcher.blade.php
> +            <div class="flex flex-row gap-2 cursor-pointer" id="current-language">
removed flag images completely

2024-03-11 08:48 UTC, purplena commented on resources/views/components/navbar.blade.php
> +                    <a href="/">
done!

2024-03-13 12:17 UTC, stephdotnet approved these changes

2024-03-13 12:17 UTC, stephdotnet commented on resources/css/_navbar.scss
> +
to remove ?

2024-03-13 12:17 UTC, stephdotnet commented on resources/js/app.js
T'as enlevé le smooth scroll ?

2024-05-15 19:14 UTC, stephdotnet requested changes
Todo
- [x] Changer le titre de la PR (pour être conventional commit)
- [x] Mettre la fonction swiper dans un fichier à part
- [ ] Essayer de build (pour vérifier que les dependencies fonctionnent)

2024-05-15 19:14 UTC, stephdotnet commented on package.json
>          "tailwindcss": "^3.4.1",
Mettre les dépendances dont tu aura besoin apres le build dans "dependencies"

2024-05-15 19:14 UTC, stephdotnet commented on resources/css/_5_projects.scss
> +    //     margin-right: auto;
A supprimer ?

2024-05-16 09:35 UTC, purplena commented
> Todo
> 
> * [x]  Changer le titre de la PR (pour être conventional commit)
> * [x]  Mettre la fonction swiper dans un fichier à part
> * [x]  Essayer de build (pour vérifier que les dependencies fonctionnent)

For Tailwind: **Tailwind CSS should typically be installed as a devDependency** because it's primarily used during development for building your stylesheets and not needed in the final production build of your application
For SASS: Once the Sass files are compiled into CSS, the resulting CSS files are what get deployed to production servers. Therefore, **Sass itself is not needed in the production environment** because the browser cannot interpret Sass syntax; it requires the CSS output.
For axios: I have put in the dependencies

2024-05-16 16:58 UTC, stephdotnet approved these changes
Good job

2024-05-16 16:59 UTC, merged